# File: playbooks/pihole-dns-reccords-manager.yml
# Description: Ansible playbook for managing PiHole DNS records
# Author: Lucas Janin
# Date: 2025-03-03

- name: Auto setup hosts on PiHole
  hosts: all
  become: true
  become_method: sudo
  vars:
    # Dynamic discovery variables
    dev_hostnames: "{{ ansible_play_hosts_all }}"
    dev_ips: "{{ ansible_play_hosts_all | map('extract', hostvars, 'ansible_host') | list }}"

  tasks:
    - name: ansible-role-pihole-dns-reccords-manager
      include_role:
        name: ansible-role-pihole-dns-reccords-manager
      run_once: true